#!/bin/sh
#

sudo apt-get update

# Packages that are needed to be able to create the MAAS lxc container for
# testing.
#
pkgs="python-httplib2 python-maas-client python-bson"
sudo apt-get install --yes $pkgs
